### ISSUE TITLE
Add Netlify Recaptcha?

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/Stone-CSS-Website#1]
Can we have Netlify recaptcha added to the get early access button without having the recaptcha under or above the button?

It should be visible when someone fills the email and clicks submit

**Comment by Diem0n** [comment]
I would like to work on this component can you assign me this issue?

**Comment by devarshishimpi** [comment]
@Diem0n Done and Thanks.

**Comment by devarshishimpi** [comment]
Fixed

**Comment by Diem0n** [comment]
@devarshishimpi thank you!i would like to point out that you are using px as units for element properties this leads to many scaling issues I suggest you should use rem units instead of pixels as they scale with view ports easily.

**Comment by devarshishimpi** [comment]
@Diem0n 
> thank you!i would like to point out that you are using px as units for element properties this leads to many scaling issues I suggest you should use rem units instead of pixels as they scale with view ports easily.

Hey, Thanks for the updates. As of what I see from the website as a landing page for early access for the Final CSS framework being developed it looks great. But, certainly your point has been noted and will be worked on!!!
