### ISSUE TITLE
Add Terms Of Use

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/Stone-CSS-Website#13]
Terms Of Use Link Does not work.

**Comment by shashikantdev3** [comment]
Hey @devarshishimpi, Do you want a generic Terms of Use or Do you have specific Terms.

Please let me know the details and assign it to me. Will update/add the Terms of Use.

**Comment by devarshishimpi** [comment]
Hi @shashikantdev3 ,

A generic Terms of use works as far as with the source code being Open Source.

Yes, I can assign it to You.

Thanks,
Devarshi Shimpi

**Comment by shashikantdev3** [comment]
@devarshishimpi, thanks! I'm on it.

**Comment by ArjunSharda** [comment]
I think this has to be closed since a terms of service has been added.

**Comment by devarshishimpi** [comment]
> I think this has to be closed since a terms of service has been added.

@ArjunSharda This will be closed after adding CSS to the Terms Of Service as currently it's just Plain HTML.
