### ISSUE TITLE
Website link in README.md

### ISSUE THREAD

**Issue by 31Sanskrati** [devarshishimpi/Stone-CSS-Website#23]
Problem:
I was looking into the project and **it took a lot of time to find the URL for the website.**

Solution:
If you can **add the URL in the README.md file** then it saves some time to open the website. And it will give easy access to look into the project.

**Comment by devarshishimpi** [comment]
Hey @31Sanskrati ,

That's a great update. Will be updated soon.

Thanks.

**Comment by devarshishimpi** [comment]
Fixed.
