### ISSUE TITLE
Mobile Responsiveness: Text doesn't fit correctly on the screen

### ISSUE THREAD

**Issue by mikkoaukusti** [devarshishimpi/Stone-CSS-Website#28]
On smaller devices, the big text doesn't fit correctly on the screen.

Here is also a screenshot about the problem (iPhone SE):
![image](https://user-images.githubusercontent.com/112617563/187936251-6fac2409-4624-410d-80f8-40117effbbda.png)

**Comment by devarshishimpi** [comment]
@mikkoaukusti Thanks For Pointing Out!! This issue will be worked on shortly in the next 2 days.

Meanwhile, you can visit [stonecss.com](https://stonecss.com/) and fill out your email for the waitlist!!

**Comment by devarshishimpi** [comment]
Fixed On iPhone SE and similar smaller devices

![image](https://user-images.githubusercontent.com/43378923/188074528-0e34ad31-6107-4fd9-9069-f5ba1c2962d9.png)

**Comment by devarshishimpi** [comment]
Fixed https://github.com/devarshishimpi/Stone-CSS-Website/pull/29

**Comment by devarshishimpi** [comment]
Fixed On iPhone SE and similar smaller devices

![Fixed On iPhone SE and similar smaller devices](https://user-images.githubusercontent.com/43378923/188075261-d4b60f5e-36f2-43f8-84d7-f8005dc55c37.png)
