### ISSUE TITLE
privacy policy/ terms of service page

### ISSUE THREAD

**Issue by Matthieu-ui** [devarshishimpi/Stone-CSS-Website#30]
The text on these pages run the entire page - does not display properly especially on larger displays.

1. Go to [https://stonecss.com/privacypolicy.html]( https://stonecss.com/privacypolicy.html)

**Comment by Matthieu-ui** [comment]
There also seems to be a scary amount of inline styles on these pages. Has anyone looked into this?

**Comment by Matthieu-ui** [comment]
I can clean this up quite a bit if you're open to it!

**Comment by devarshishimpi** [comment]
> The text on these pages run the entire page - does not display properly especially on larger displays.
> 
> 1. Go to https://stonecss.com/privacypolicy.html

Thank You, This issue was a part of the roadmap but not a problem to be fixed.

**Comment by devarshishimpi** [comment]
> I can clean this up quite a bit if you're open to it!
Sure, I have assigned you the same.

**Comment by devarshishimpi** [comment]
Fixed in https://github.com/devarshishimpi/Stone-CSS-Website/pull/35
