### ISSUE TITLE
Add Twitter Card

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/Stone-CSS-Website#31]
Add Twitter OG Meta Tags to the website for Better SEO on Twitter

**Comment by nightfury-crypto** [comment]
Hey! I want to contribute in this issue. Please assign it to me. Thanks

**Comment by devarshishimpi** [comment]
> Hey! I want to contribute in this issue. Please assign it to me. Thanks

Sure.

**Comment by devarshishimpi** [comment]
Fixed in https://github.com/devarshishimpi/Stone-CSS-Website/pull/44

**Comment by devarshishimpi** [comment]
Half Fixed

**Comment by nightfury-crypto** [comment]
> Half Fixed. I'll add the Twitter tag to the rest pages myself. As well as fix the code lines.

Hey! I can try to fix this. Actually I have not changed any code the vs code formatted the code by it's own and I can fix this. Can i give a try?

**Comment by devarshishimpi** [comment]
> > Half Fixed. I'll add the Twitter tag to the rest pages myself. As well as fix the code lines.
> 
> Hey! I can try to fix this. Actually I have not changed any code the vs code formatted the code by it's own and I can fix this. Can i give a try?

Sure.

**Comment by nightfury-crypto** [comment]
@devarshishimpi Hey you need to verify and if everything is ok then merge it asap otherwise it will create conflict. **urgent**
 #47

**Comment by devarshishimpi** [comment]
> @devarshishimpi Hey you need to verify and if everything is ok then merge it asap otherwise it will create conflict. **urgent** #47

Has been merged.
