### ISSUE TITLE
Update Canonical URLs

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/Stone-CSS-Website#32]
Add Canonical URLs To All the pages for better SEO

**Comment by taanii** [comment]
Hey,
Can I work on this issue?

**Comment by devarshishimpi** [comment]
Yes, Sure.

**Comment by taanii** [comment]
Hey @devarshishimpi , 
What format of canonical URL do you find most suitable for this project? Pls add a comment about it so that I can add all the URLs

**Comment by devarshishimpi** [comment]
> Hey @devarshishimpi , 
> What format of canonical URL do you find most suitable for this project? Pls add a comment about it so that I can add all the URLs

@taanii I would want it to the main url without the `.html` at ending.

**Comment by devarshishimpi** [comment]
@taanii Where's the development reached? Could I receive the PR within the next 2 days?

**Comment by taanii** [comment]
Hey @devarshishimpi  I've added the canonical URLs using the default syntax for it, but as the site is not hosted at my side, I'm not able to see if the feature is working or not. 

I've created canonical URLs for five pages:
1. index.html
2. terms.html
3. privacypolicy.html
4. contct.html
5. 404.html

I'll create a PR and you can check it in the development branch.

**Comment by devarshishimpi** [comment]
@taanii Merged the PR. Yes, the site is working fine and I received the Canonical URLs in the method I wanted.

Thanks Again!!!
