### ISSUE TITLE
Hide Index.html from the URL

### ISSUE THREAD

**Issue by Nishaaaanth** [devarshishimpi/Stone-CSS-Website#40]
In the Homepage if you click on the logo it proceeds to 'index.html' if you take look at the URL. Normally, this shouldn't happen instead should refresh the site as it is.

**Comment by Nishaaaanth** [comment]
I can contribute here. Thanks.

**Comment by devarshishimpi** [comment]
> In the Homepage if you click on the logo it proceeds to 'index.html' if you take look at the URL. Normally, this shouldn't happen instead should refresh the site as it is.

Hi, Thanks For Pointing out.

**Comment by devarshishimpi** [comment]
> I can contribute here. Thanks.

@Nishaaaanth Sure have assigned you the same. This is not just for the `index.html` page, but all of the other pages too like privacy policy, terms of service and contact page.

**Comment by Nishaaaanth** [comment]
Sure @devarshishimpi. But, to remove .html extension from other subpages requires a .htaccess file to be created inside your server manager.

**Comment by devarshishimpi** [comment]
Definitely.

**Comment by devarshishimpi** [comment]
> In the Homepage if you click on the logo it proceeds to 'index.html' if you take look at the URL. Normally, this shouldn't happen instead should refresh the site as it is.

Fixed in https://github.com/devarshishimpi/Stone-CSS-Website/pull/41
