### ISSUE TITLE
Why this css part is there ? There is no h7 or h8 tag in html

### ISSUE THREAD

**Issue by nightfury-crypto** [devarshishimpi/Stone-CSS-Website#48]
![image](https://user-images.githubusercontent.com/65121678/192150533-75c81a67-a483-410e-9ff4-9ce5d8abc4b4.png)

**Comment by devarshishimpi** [comment]
`<h8>` is present on the contact page. `<h7>` will be removed

**Comment by devarshishimpi** [comment]
And Fixed!!
