### ISSUE TITLE
#second to #features and changes with that

### ISSUE THREAD

**Issue by cytronicoder** [devarshishimpi/Stone-CSS-Website#8]
When the user is directed to the features section, the URL is `https://stonecss.netlify.app/#second`. Instead, it should be `https://stonecss.netlify.app/#features`. The `second` ID should become a class, while `features` should be the ID for that specific section (and we should also make the necessary changes in the CSS file).

**Comment by devarshishimpi** [comment]
Noted. I will update the same and all the classes and ids for the same.
